version: '3'
services:
  example-service:
    image: minio/minio:RELEASE.2022-03-24T00-43-44Z
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    command:
      - gateway
      - s3
      - https://s3.eu-west-1.amazonaws.com
      - --console-address
      - :9001
    networks:
      - internal
    dns:
      - 10.10.0.100
    # required if you want to connect to AWS services via SSL
    volumes:
      - "certificates:/etc/ssl/certs/:ro"
    labels:
      - "virtual.host=example-service.test"
      - "virtual.port=9001"
      - "virtual.tls=internal"
