version: '3'
services:
  aws-cli:
    build: aws-cli
    environment:
      AWS_ACCESS_KEY_ID: FAKE
      AWS_SECRET_ACCESS_KEY: FAKE
      AWS_DEFAULT_REGION: eu-west-1
    networks:
      - internal
      - default
    dns:
      - 10.10.0.100
    volumes:
      - "certificates:/etc/ssl/certs/:ro"